name: json2html
region: sgp
static_sites:
- environment_slug: html
  github:
    branch: master
    deploy_on_push: true
    repo: bloopletech/json2html
  name: json2html
  build_command: npm run build
  routes:
  - path: /